### ISSUE TITLE
"Use locally cached display styles" alters the position of images on the right

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-js-windows#255] opened 2022-04-28 14:03 UTC
This was not always the case. Something must have changed with the latest tweaks.

Top with `Use locally cached display styles` disabled, below enabled:

![ZomboDroid 28042022143843](https://user-images.githubusercontent.com/71934042/165754262-4f1c5d5c-ebda-4f01-a38a-2ecaea47ad83.jpg)

Even with `Use locally cached display styles` enabled, it was never like this until a few months ago when I updated the application.

[Compare](https://github.com/kiwix/kiwix-js-windows/issues/221#issue-1088277775) the pictures of the same article from then and now. Same settings.

Then:

![147339967-f310a4cd-2f4b-4604-8ad5-11e35156b48c](https://user-images.githubusercontent.com/71934042/165760711-88276df6-b1d7-466c-8717-bdd5a60b3739.jpg)

Now:

![Screenshot_20220428-150734_Samsung Internet Beta](https://user-images.githubusercontent.com/71934042/165760592-3b5af60b-e5e8-4fa4-a857-9c3d1b928273.jpg)

And this is where it becomes a problem.

`Use locally cached display styles` enabled:

![Screenshot_20220308-145634_Samsung Internet](https://user-images.githubusercontent.com/71934042/157256018-22e0c216-a819-4416-bbb9-ade36b065dd6.jpg)

Disabled:

![Screenshot_20220428-152544_Samsung Internet](https://user-images.githubusercontent.com/71934042/165763158-e1cac250-daba-476a-99d0-365e837a0e61.jpg)

I have disabled `Use locally cached display styles` for the German Wikipedia without any losses, but doing the same for the English Wikipedia would have a negative impact on templates...

**Comment by Jaifroid** [comment] 2022-04-28 15:49
Ah, interesting. I wonder if this is related to a tweak for the MDwiki archive. See #232. I'm sure this is quite an easy fix. Will take a look.

**Comment by Jaifroid** [comment] 2022-04-28 15:51
@Inbefortus Could I just check which German Wikipedia ZIM you are using?

**Comment by Inbefortus** [comment] 2022-04-28 15:59
@Jaifroid 2022-03 German Wikipedia.

- https://farm.openzim.org/pipeline/9663e3d241c478d5147c1226

**Comment by Jaifroid** [comment] 2022-05-01 10:23
@Inbefortus As I suspected, the cause of this is the style correction made to support the new MDwiki ZIMs. See https://github.com/kiwix/kiwix-js-windows/issues/232#issuecomment-1054538480 to understand why it was made (the captions fill the space to left of image if not corrected). I'm looking into making this an MDwiki-specific correction until the MDwiki ZIMs are corrected at source.

**Comment by Jaifroid** [comment] 2022-05-01 11:09
@Inbefortus Could you kindly test your ZIM on the development PWA: https://kiwix.github.io/kiwix-js-windows/ , making sure that the PWA has updated to version 1.9.85 before you start the test? I downloaded a copy of the ZIM, and have tested some of your pages with this change, but it would be good to corroborate.

If you have trouble updating the Dev app to 1.9.85, you can always use the Reset button in Config. It will only reset the dev PWA, not the production version. It should inform you that it is on v1.9.85, or you can check in About.

**Comment by Jaifroid** [comment] 2022-05-01 11:10
PS Fix is in https://github.com/kiwix/kiwix-js-windows/commit/a056016ebd74b30a50889a04a25e01ff79e64c31.

**Comment by Inbefortus** [comment] 2022-05-01 11:43
@Jaifroid I can confirm that your adjustment has worked. Thank you!
Now it is much more enjoyable again. Some articles looked partially chaotic. But I understand that it had to be that way because of MDwiki.

> until the MDwiki ZIMs are corrected at source.

Let's hope that this is the case soon.

**Comment by Jaifroid** [comment] 2022-05-01 13:16
OK, great, thanks for testing. I'll be releasing a new version (and updated production PWA) later today.

**Closed by Jaifroid** 2022-05-01 13:16 UTC
Labels: bug/non-critical
