### ISSUE TITLE
ZIM download apparently broken on Xbox

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js-windows#21] opened 2017-11-30 19:55 UTC
Reported here https://lists.wikimedia.org/pipermail/mobile-l/2017-November/010589.html

> > > I noticed it's labeled as compatible with the whole range of Windows
> > > devices including Xbox, so I had to try it on my Xbox One too... It does
> > > run! However the download links don't work -- they bring up the
> > > index/list view of articles instead. Interface could be better
> > > controller-optimized too, it basically emulates a mouse cursor by
> > default.
> >
> > Thank you Brion for this fresh testing feedback... you confirm that the
> > inability of the app/system to download a ZIM file (one time you have
> > clicked on a link) is a Xbox specific problem?
> >
> 
> Didn't have the problem on the phone, so I assume Xbox-specific. I don't
> have a dev setup on my Xbox at the moment to run unsigned builds, but would
> be happy to test further when time permits. :) (Supposedly the dev mode
> switch is not too difficult to turn on/off.)

**Comment by Jaifroid** [comment] 2017-11-30 20:17
Ah, very helpful report. I don't have an Xbox, glad to hear it runs. Not sure how I can test / debug the download issue -- it should open a browser window.

Three options: find someone willing to test and debug; add a disclaimer that it "should" run on Xbox but there have been reports that download links are broken; or mark it as not compatible with Xbox (I think this would prevent it from being downloaded and installed for Xbox from the Store).

Any thoughts, @kelson42 ?

**Comment by kelson42** [comment] 2017-11-30 20:20
Lets wait a bit, maybe we can gather a bit more information from users. But otherwise, I would tend to avoid distribution on Xbox. Up to you.

**Comment by brion** [comment] 2017-11-30 20:38
(Reporter here, I can test a little more if needed!)

I'd probably recommend marking it not compatible with Xbox for now; you should be able to switch that back on in the future if the problem is resolved in a future build.

**Comment by Jaifroid** [comment] 2017-11-30 21:00
OK, great, thanks @brion. I'll do this. Will issue an update this weekend after I've resolved #18 and #20 , and will remove Xbox compatibility then.

**Comment by Jaifroid** [comment] 2017-12-02 09:00
@brion I'm looking into this, and wondered what your advice would be about disabling mouse mode on the Xbox and enabling directional controller navigation. I have found the following info from Microsoft:

> HTML
> To turn on directional controller navigation in a JavaScript Universal Windows Platform (UWP) app, use the TVHelpers directional navigation JavaScript library. Include the directional navigation JavaScript file in your app package, and add a reference to it in all of the HTML pages that require directional controller navigation:
> `<script src="directionalnavigation-1.0.0.0.js"></script>`
> For more details, see the directional navigation wiki.

From what I understand, you're saying that the app basically works on Xbox, but that navigation is clumsy due to the mouse mode emulation and that download links are broken. If the latter is the main issue, then if, say, we were to release a packaged version of Wikimed or Wikivoyage, the download issue wouldn't be a problem (as the ZIM would come with the app, as the Ray Charles one currently does). So that would leave the clunky navigation as the main issue with the Xbox. If directional controller navigation is as easy to enable as the MS doc seems to suggest, would it improve the experience?

I'm interested in keeping Xbox compatibility because I understand that there is no possibility any more of running x86 apps on that platform, meaning that Kiwix JS would be the only app supporting Kiwix on Xbox.

**Comment by Jaifroid** [comment] 2017-12-02 09:07
@brion - sorry, just one more thing: the download links are, literally, just links. I.e., download of a ZIM file does not occur in the app, it works by launching a browser (Edge on Windows Mobile, whatever is configured as the main browser on a tablet), and the download is undertaken by the browser. Are you able to let me know how browsing and download of files are handled on Xbox systems? Is it possible to download Zipped files, for example? Or a torrent? I provide torrent links, for example. I'm trying to understand why clicking on a link to a ZIM file does not open a browser window, and whether there might be a simple fix (like designating a target for the link).

**Comment by kelson42** [comment] 2017-12-31 13:55
@Jaifroid @Popolechien Could we meanwhile remove the xbox support in the Microsoft app store? It seems to be still there?

**Comment by Jaifroid** [comment] 2017-12-31 14:39
Yes, I delayed on this because I was trying to ascertain whether the issue is only really with the download links (which are provided as a convenience -- the user can always just get their ZIM from kiwix.org instead) or whether it is something more fundamental. My main worry with disabling it is that we may never get any further feedback at all if no-one can install it to try it out. However, if having Xbox support is not of particular interest to Kiwix, I can disable it on next update.

**Comment by kelson42** [comment] 2018-01-03 19:01
@Jaifroid I understand your concern. To give us a chance to reproduce the problem, identify the root cause and maybe fix the problem... and therefore avoid to drop the Xbox support... I have ordered a second-hand Xbox. I'll be back on that ticket en of January.

**Comment by Jaifroid** [comment] 2018-01-03 20:33
Ah thanks @kelson42  -  Xbox One is the model that has Windows 10, Store and Apps from what I understand.

**Comment by Jaifroid** [comment] 2018-01-03 20:49
Just a thought: if the issue is to do with downloading ZIMs on Xbox, then the custom app(s) ought to be OK (if a bit clunky?) on Xbox One, since they come with the ZIM included. This is another good reason for implementing #38 .

**Comment by kelson42** [comment] 2018-01-21 17:36
@Jaifroid I finally got an xbox one to test. I can reproduce the/a problem.
1 - Click on "Open library" button
2 - The list of directories is display like available here https://download.kiwix.org/zim/
3 - But if I click on a link (for example "Vikidia") then the whole "settings" panel disappear and the last visited article is displayed.

**Comment by Jaifroid** [comment] 2018-01-21 18:54
OK, that's helpful @kelson42 . Many thanks for obtaining the hardware and testing.

So, in principle we wouldn't have a problem with the Wikivoyage (and upcoming WikiMed) apps, since they hide the download links along with the file selectors.

Potential solutions / workarounds:

1. When an Xbox user attempts to open the Library in the app, instead redirect user to kiwix.org to download their ZIM files (this is a workaround -- I'm sure I can find how to detect if the app is running on Xbox);

2. Permanenty hide the download links when running the app on Xbox and make clear elsewhere in the app that the functionality doesn't work on Xbox;

3. Try to fix it! I would need to investigate if there is a VM version for devs, so that I can at least debug, and you can then test on hardware - so this may be longer term;

4. Stop supporting Xbox in Kiwix JS. Optionally keep Xbox compatibility for Wikivoyage and WikiMed. This depends on your further tests as to the useability of the packaged apps.

**Comment by kelson42** [comment] 2018-01-21 18:55
@Jaifroid I have also tested Wikivoyage and indeed it seems to work well.

**Comment by Jaifroid** [comment] 2018-01-21 19:06
That's good news, thanks @kelson42! 

So it might be worth, in the short to medium term, trying 1 above and if that proves difficult, opt for 4.
3 (fixing it) is something I'll investigate, but would take longer depending on the development tools for Xbox debugging.

In fact, I'm pretty sure there's a simple test for Xbox, because I seem to remember Microsoft documents it somewhere and I found it previously.

**Comment by kelson42** [comment] 2018-01-21 19:08
@Jaifroid I would try to get help here, by asking Microsoft dev center or similar.

**Comment by brion** [comment] 2018-01-21 19:22
Visual Studio should be able to deploy to and debug the app on device (if the Xbox One is switched into development mode), but I've never attempted this myself. :) Wouldn't hurt to get in touch with MS but I think my contacts there are long out of date.

**Comment by Jaifroid** [comment] 2018-02-13 07:45
@kelson42 No rush, but in due course could you test the latest [WikiMed 0.9.9 beta](https://www.microsoft.com/store/apps/9PHJSNP1CZ8J) (version in the Microsoft Store) on Xbox? As it hides the download links, hopefully it shouldn't suffer from this issue. But it would be good to test it for navigability and to uncover any other issues not related to download links.

**Comment by kelson42** [comment] 2018-06-10 14:01
@Jaifroid I have finally tested again:
* List of contents does not appear on Wikivoyage and WikiMed apps
* Downloading through IE works too :+1: 

Well done.

**Comment by Jaifroid** [comment] 2019-05-19 07:36
@kelson42 I've noticed a few poor reviews from Xbox users, complaining at the lack of keyboard support. Here is the most informative of these reviews:

> Available on PC, yet keyboard and mouse support on console version is unheard of? Oh, okay then?!! Also, why would you need Wikipedia offline.....on a console which was planned to be ALWAYS ONLINE??? It's a nice idea, but it doesn't work on Xbox One. Also, before you go or rate this review or do whatever, have a fun fact. Kiwix is bad. Have a nice day.

These reviews give extremely low ratings (1* and 2*). The other device-type reviews are almost all 4* or 5*. Overall rating is 4.5*. Should I suspend Xbox support? I don't think it should go to a Version 1.0 on Xbox (i.e., shouldn't come out of Beta), unless I can find a way to add keyboard and mouse support for the console.

**Comment by kelson42** [comment] 2019-05-19 17:34
@Jaifroid I'm not sure if this is related, but I have remarked that files coming from https://ftp.acc.umu.se/ didn't have the proper HTTP header to allow a download, so the file was directly displayed in the browser. I have open a bug here https://github.com/kiwix/maintenance/issues/63 and contacted the mirror master.

**Comment by Jaifroid** [comment] 2019-05-19 18:47
Thank you, @kelson42 . Occasionally the servers are misconfigured. Thanks for noticing this and for opening a bug report.

I'm not sure file download is the issue (any more) with Xbox users so much as their not being able to use the keyboard and mouse (if they have these plugged in), and can only use Kiwix in Console mode. But then, as the user above says, it doesn't seem like offline access is a big need for Xbox, because it is designed to be always online. I don't know if that's true or not!

**Comment by kelson42** [comment] 2020-01-05 11:30
I propose to close that one for the moment because there is nothing more we can do here and things seems to work as long as server is properly configured.

**Comment by Jaifroid** [comment] 2020-01-05 12:24
Agreed. I was hoping at some stage to add keyboard support, but can re-open if that seems a realistic possibility.

**Closed by Jaifroid** 2020-01-05 12:24 UTC
Labels: bug

**Comment by kelson42** [comment] 2020-01-05 13:22
@Jaifroid I would recommend to open a dedicated ticket for the keyboard support.
