### ISSUE TITLE
Last-visited page is not remembered if archive is picked with "Select single archive" button

### ISSUE THREAD

**Issue by fhvr40** [kiwix/kiwix-js-windows#37] opened 2018-01-03 14:55 UTC
I checked this setting in Windows 10 Mobile and Windows 10 Desktop, but Kiwix JS reopens with the start page of my wikipedia_de_all_2017-02.zim on both platforms.

**Comment by kelson42** [comment] 2018-01-03 16:06
@fhvr40 I'm not the maintainer of the app, but I can not reproduce the problem neither on Windows mobile nor on Windows 10 Desktop. Maybe you maybe share a detailed step-by-step procedure to reproduce the problem?

**Comment by fhvr40** [comment] 2018-01-04 10:10
Thank you for your responses!
The issue is reproducable with my devices. Here some details:

W10M:
HP x3, v1709, build 10.0.15254.124
Kiwix Js installed on device storage (C), wikipedia_de_all_2017-02.zim on MicroSD (D), manually registered to Kiwix JS in settings.

W10Pro:
Lenovo Yogabook, v1709, build 16299.125
Kiwix Js installed on device storage (C), wikipedia_de_all_2017-02.zim on MicroSD (D), manually registered to Kiwix JS in settings.

I open Kiwix, search and go to a subject, close Kiwix, reopen and get the startpage of ZIM (Remember last-visited page is ticked, I use dark mode and dark theme on both devices).

It is not a big issue to me, but I want to help improve the app, I hope my details help a little. It is a great gift to me using Offline Wikipedia an W10M. And on Desktop the new UWP is much faster than the old x86 version, so overall it is a great improvement, thanks to all developers here! 

@Jaifroid: where did you download wikipedia_de_all_2017-12.zim?
The newest version I found is from June 2017 - https://dumps.wikimedia.org/other/kiwix/zim/wikipedia/

**Comment by Jaifroid** [comment] 2018-01-04 10:38
Thank you @fhvr40 , I'll investigate and get back to you. It's great to have your report.

Apologies, I was confused and I was actually testing against the `wikivoyage_de_all_novid_2017-12.zim`. I've now downloaded `wikipedia_de_all_novid_2017-08.zim` in order to test this issue. That ZIM is available from here: http://download.kiwix.org/zim/wikipedia/

**Comment by Jaifroid** [comment] 2018-01-04 10:39
And you can get a torrent for the file here:
http://download.kiwix.org/zim/wikipedia/wikipedia_de_all_novid_2017-08.zim.torrent

**Comment by fhvr40** [comment] 2018-01-04 11:06
@Jaifroid: Thank you!

**Comment by Jaifroid** [comment] 2018-01-04 11:28
@fhvr40 I can't reproduce with the latest German Wikipedia ZIM, though actually it should not be dependent on the ZIM at all.

What may have happened is that some erroneous entry has been saved to the cookie. Could I ask you to try the following in order, until / if the issue is resolved?

1. Untick the option to remember the last-visited page. Go back to the home page. Visit any other page, wait till the page is loaded, then exit the app completely. Go back into the app (should open at the start page of the ZIM), go to Configuration, tick the option to remember the last-visited page, go back to home, visit another page, and test if this has cured the problem. Expected result is that the cookie gets cleared (by unticking the option) and a new, correct value is stored in it when you re-tick the option.

2. If above doesn't work, go to Configuration, tap the Select Storage button, and the built-in Ray Charles ZIM should load. Visit some pages in Ray Charles, and check if the option is working with that ZIM. Expected result is that it should work with Ray Charles, and loading Ray Charles will also clear the cookie. If it works with Ray Charles, go back to Configuration, tap Select Storage again, and use the appropriate selector to pick the German Wikipedia ZIM or its folder, and test if it works now.

3. Final option would be to uninstall the app (right-click its icon or long-press it, and choose uninstall), then re-install from the Store. Your separately downloaded ZIMs won't be deleted. (You shouldn't need to register ZIM files to the app manually, by the way. There's no particular advantage, as the app can't currently load a ZIM by double-clicking the ZIM file. However, it shouldn't do any harm!)

**Comment by fhvr40** [comment] 2018-01-04 12:53
@Jaifroid OK, I did 1.-3. on mobile and 1.-2. on PC. With built-in Ray Charles.zim all works fine on mobile and PC, the issue is there again with wikipedia_de_all_2017-02.zim, no matter what I do. I will be at home again on Saturday and will download the 2017-08.zim you recommended to report again, maybe it is ok with my devices with the new zim-version.

**Comment by Jaifroid** [comment] 2018-01-04 13:05
@fhvr40 Thanks, that narrows it down at least. It could be that ZIM version, then, although it would be unexpected for the ZIM to matter! I'll see if I can test against that version too, as discovering the cause of this error might help to ensure it doesn't happen with other, unknown ZIM types.

**Comment by Jaifroid** [comment] 2018-01-04 15:59
@fhvr40 I've been able to reproduce your issue!

It is not the ZIM, it's the manner of picking the ZIM. Because I have lots of ZIMs on my hard drive, I keep them all in a folder, and I use the option to Select folder (after tapping Select storage), and hadn't fully tested it with the "Select single archive" button.

So, the workaround is to select the archive by using "Select folder" rather than "Select single archive". I've confirmed this issue with more than just your archive -- the issue affects any archive picked with the "Select single archive" button.

I'll fix this issue and it will be updated in the store with the next update, which should be Beta 0.9.7.

Thank you very much for this report. I'll put a note here when its fixed in source.

**Comment by fhvr40** [comment] 2018-01-04 16:31
@Jaifroid You are right, I always selected the file. If I select a folder I can confirm it reopens the article on PC and mobile. Thank you for your support!

**Closed** 2018-01-05 15:38 UTC
Labels: bug

**Comment by Jaifroid** [comment] 2018-01-05 15:41
@fhvr40 This is now fixed in source according to my tests. The fix won't appear until the app gets updated in the Store, which won't now be till next week, but the app should notify you on next launch if it's been updated. After that, let me know if you continue to experience the issue.

**Comment by fhvr40** [comment] 2018-01-12 08:42
@Jaifroid I tested with new version 0.9.7 and reopening works fine on desktop and mobile when selecting a single file. Good work! Franz

**Comment by Jaifroid** [comment] 2018-01-12 08:56
Great, thanks for confirming @fhvr40 !
