### ISSUE TITLE
Release filenames for Kiwix JS Electron

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js-windows#243] opened 2022-03-13 14:39 UTC
I see a new directory has appeared at https://download.kiwix.org/release/kiwix-js-electron/ with builds of Kiwix JS using Electron and packaging for different kind of OSes. This is great.

But the filename are not OK and don't fit to the standard we apply for other releases:
* No uppercase
* I don't understand where the `E` in `kiwix-js-electron_1.9.3-E_amd64.deb` comes from (and therefore seems confusing to me).
* Architecture should be before the version number.
* Not really a big problem, but we tend to use `x86_64` or `x64` in place of `amd64` (which IMO is a bit misleading)

I would recommend something like `kiwix-js-electron_x64_1.9.3.deb` in place of `kiwix-js-electron_1.9.3-E_amd64.deb`.

**Comment by Jaifroid** [comment] 2022-03-13 15:39
Ah OK, yes I can rename these in the publishing script.

* These files are named by [electron-builder](https://www.electron.build/) and this is how they are when that script builds them. I didn't change their names. Electron-builder puts the architecture is after the version number
* The `-E` comes from the version number in `package.json`. `-E` represents a "channel" of the app, which is the "Electron" channel.

It's not a problem to rename them with a simple regex.

**Comment by kelson42** [comment] 2022-03-13 15:50
@Jaifroid I can renamed the old files one we agree on a scheme. But I can not change the CD.

**Comment by Jaifroid** [comment] 2022-03-13 20:08
@kelson42 I'm working on it... Just added the NWJS build, next will tackle the renaming.

**Comment by Jaifroid** [comment] 2022-03-14 09:25
@kelson42 Could you kindly review the filenames in the latest nightly (also in screenshot below), and let me know of any further changes you'd like. To summarize:

* I changed everything to lowercase except the channel names, which are part of the app's package identification, and -XP-, as I want the XP to stand out (so users don't accidentally download this very old XP implementation)
* I swapped the architecture and the build version info
* I changed AMD64 to x86_64
* I didn't change i686 because technically that's different (I understand), and probably has specific meaning for RPM users

![image](https://user-images.githubusercontent.com/4304337/158142625-f7532113-fe54-4c63-9dea-84ce4e730e73.png)

**Comment by kelson42** [comment] 2022-03-14 09:30
* I would remove the `E`, we know this is `kiwix-js-electron`.
* I would put unterscores beween parts (in place of dashes), so `kiwix-js-electron_i386_1.9.4_xyz.deb`
* `kiwix-js-electron_i386_xyz.deb` would be better than `kiwix-js-electron_i386_1.9.4_xyz.deb`. Latest version is confusing
* I assume it would be `kiwix-js-electron_i386_1.9.4.deb` for the release?

**Comment by Jaifroid** [comment] 2022-03-14 09:59
OK, thanks, I'll try to work it out!

**Comment by Jaifroid** [comment] 2022-03-14 10:02
> * I assume it would be `kiwix-js-electron_i386_1.9.4.deb` for the release?

Yes, that's the idea. I'll test release versions only once I've got the nightlies right. It's the same scripts (one bash, one PowerShell), so if they're written correctly they should produced the same result without the commit SHA and extra hyphen.

**Comment by Jaifroid** [comment] 2022-03-15 06:39
This is latest format (screenshot below from [latest nightly](http://download.kiwix.org/nightly/2022-03-15/)).

Rationale:

* Underscores are used to separate conceptual parts of the name, i.e. `appname_architecture_type_SHA.ext`
* Hyphens are used *within* each of these parts, like `kiwix-js-electron` and `x86-64`.

Is this OK now? By the way, I notice that the server is missing filetype icons for the Linux binaries. The same one as for .exe could be used.

![image](https://user-images.githubusercontent.com/4304337/158319738-05bb394a-1627-4de1-83d3-fc87e98f9afa.png)

**Comment by kelson42** [comment] 2022-03-15 19:33
Even better, but:
* NWJS filenames should be lowercase
* `ia32` should be `i386` to be coherent
* I don't think this is only for Windows XP, I would just write `win` or `windows`
* This should give something glike `kiwix-js-nwjs_windows_i386_xyz.zip`

**Comment by Jaifroid** [comment] 2022-03-16 00:21
@kelson42 The XP version is intended only for XP and Vista. The Chromium browser in it is obsolete and slow, and can't do Service Worker mode, so I really would like to limit it and signal through the filename that it is only for XP. I do, however, have some users of this version (they write to me about it)!

I'll change ia32 to i386, and will make NWJS lowercase and move it.

I'm a bit confused about the differences between these various architectures and whether the name differences are significant....

**Comment by Jaifroid** [comment] 2022-03-16 11:00
@kelson42 A related question: I can now build with CI the Wikivoyage app. It takes quite a bit longer due to the large ZIM included, so I don't propose to do nightly builds (it would be a lot of bandwidth for no good reason, as the base app is able to read the WikiMed and Wikivoyage ZIMs independently of course). However, my question is, would you want copies of the release files for these packaged apps to be made available on download.kiwix.org releases (as well as GitHub releases)?

FYI, the releases of these packaged apps are basically just the base app with the associated ZIM, and some customization of text, hiding of file pickers, etc. So it could be argued that it is enough to make the base app available on download.kiwix.org.

**Comment by kelson42** [comment] 2022-03-16 17:22
XP lowercase?

**Comment by kelson42** [comment] 2022-03-16 17:25
> However, my question is, would you want copies of the release files for these packaged apps to be made available on download.kiwix.org releases (as well as GitHub releases)?

I have difficulties to answer this question. In principle yes, but this is going to take quite a bit of storage over time. I guess we can try! But not sure we will keep all the history of releases...

**Comment by Jaifroid** [comment] 2022-03-16 18:03
> XP lowercase?

OK -- I just wanted it to stand out, as I really don't want people downloading it and using it on modern Windows... It's there very much as a service to people who really have no alternative than to run XP or Vista still.

**Comment by kelson42** [comment] 2022-03-18 08:08
@Jaifroid Thx, if that last point fixed, I think we can go forward and merge.

**Comment by Jaifroid** [comment] 2022-03-18 08:44
@kelson42 I hadn't had time to work on this yesterday, but I've just done some code update and corrected an issue with Linux not being able to read the BOM in some files (Microsoft Store requires UTF8 with BOM, Linux can't cope with it....).

I think it's all looking correct now:

![image](https://user-images.githubusercontent.com/4304337/158966474-8cf40bde-d2ca-4704-8214-b5233c94793a.png)

**Comment by kelson42** [comment] 2022-03-18 08:51
One of the appimage does not have an architecture, wich looks like a bug to me.

Otherwise looks good :)

**Comment by Jaifroid** [comment] 2022-03-18 09:12
@kelson42 Not a bug. I understand that AppImage is always 64bit unless it says otherwise? The file is produced by Electron Builder with no architecture in the name, hence I didn't add one. The 32bit file is produced with the _i386_ architecture. I don't know the Linux conventions personally, so happy to be guided.

**Comment by Jaifroid** [comment] 2022-03-18 09:16
Actually I see a different bug. One of the RPMs should be 32bit. Something funny going on there.

I'm sorry this has been so convoluted and buggy. I'm having to deal with two different scripting languages (PowerShell and bash), and every small change seems to introduce consequences later in the script. Sigh. Just let me know whether the appimage should show 64bit, and I'll deal with the other bug later today.

**Comment by Jaifroid** [comment] 2022-03-18 09:23
Ah no, I forgot _i686_ *is* a 32bit architecture. It's the end of the week...

**Comment by Jaifroid** [comment] 2022-03-19 08:09
@kelson42 Last issue to resolve is whether the standard (64bit) AppImage needs to state its architecture explicitly. If I understand correctly, the ethos of AppImage is "one app = one file" (e.g. [`VLC.AppImage`](https://apprepo.de/appimage/vlc)). It's supposed to be a "Universal" Linux package. So they only state architecture when it deviates from the 64bit norm. But I notice Kiwix Desktop does state 64bit.

**Comment by kelson42** [comment] 2022-03-19 08:10
Appimages are not universal app. Therefore, I woukd prefer to have architecture explicit in the filename.

**Comment by Jaifroid** [comment] 2022-03-19 08:47
@kelson42 OK, will do.

**Comment by Jaifroid** [comment] 2022-03-21 15:34
This happened last night. I guess we'd better not try to put an extra 5GB on with each Wikivoyage release in that case...

![image](https://user-images.githubusercontent.com/4304337/159295713-7b417a9f-1f51-4bd6-b63c-0231c34e61bf.png)

**Comment by Jaifroid** [comment] 2022-03-21 15:47
I've added x86-64 to the 64bit AppImage package, so I'm closing this issue now. Thank you for your help, @kelson42 .

![image](https://user-images.githubusercontent.com/4304337/159298432-204b54fc-0b32-4603-9ab2-630fee6c9f73.png)

**Closed by Jaifroid** 2022-03-21 15:47 UTC
Labels: build

**Comment by kelson42** [comment] 2022-03-21 17:03
@Jaifroid who renames the oder files?

**Comment by kelson42** [comment] 2022-03-21 17:19
Indeed, many things wrong in https://download.kiwix.org/release/kiwix-js-electron/

**Comment by Jaifroid** [comment] 2022-03-21 18:41
Done.

**Comment by kelson42** [comment] 2022-03-21 19:11
thx, LGTM
